# Generated by Django 5.0.4 on 2024-04-30 23:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Descripciones',
            fields=[
                ('Descripcion', models.CharField(max_length=100)),
                ('idDescripcion', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='linea',
            fields=[
                ('idLinea', models.AutoField(primary_key=True, serialize=False)),
                ('linea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tiempo_inicio', models.TimeField()),
                ('tiempo_fin', models.TimeField()),
                ('golpes', models.IntegerField()),
                ('pieza_por_golpe', models.IntegerField()),
                ('piezas_ok', models.IntegerField()),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bitacora.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Paro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paros', to='Bitacora.produccion')),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartamento',
            fields=[
                ('idSub', models.AutoField(primary_key=True, serialize=False)),
                ('subdepartamento', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartamentos', to='Bitacora.departamento')),
            ],
        ),
    ]
