# Generated by Django 5.0.6 on 2024-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0002_loginuser_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='linea',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='turno',
            field=models.CharField(max_length=12),
        ),
    ]
