# Generated by Django 5.0.6 on 2024-07-11 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0006_alter_usuario_lastname_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlitterParo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('observaciones', models.TextField(default='Sin observaciones')),
                ('duracion', models.IntegerField(default=0)),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SlitterProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tiempo_inicio', models.TimeField()),
                ('tiempo_fin', models.TimeField()),
                ('kilos_ok', models.IntegerField()),
                ('cintas', models.IntegerField()),
                ('master_coils', models.IntegerField()),
                ('hmc', models.IntegerField()),
                ('gw', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idTurno', models.AutoField(primary_key=True, serialize=False)),
                ('Turno', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='paro',
            name='produccion',
        ),
        migrations.RemoveField(
            model_name='paro',
            name='tiempo_registro',
        ),
        migrations.AddField(
            model_name='paro',
            name='observaciones',
            field=models.TextField(default='Sin observaciones'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='idDepartamento',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='descripciones',
            name='idDescripcion',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='linea',
            name='idLinea',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='idModelo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paro',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subdepartamento',
            name='idSub',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
