# Generated by Django 5.0.6 on 2024-07-11 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0007_slitterparo_slitterproduccion_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsiladoraParo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('observaciones', models.TextField(default='Sin observaciones')),
                ('duracion', models.IntegerField(default=0)),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OsiladoraProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tiempo_inicio', models.TimeField()),
                ('tiempo_fin', models.TimeField()),
                ('kilos_ok', models.IntegerField()),
                ('cintas', models.IntegerField()),
                ('rollos_osilados', models.IntegerField()),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
            ],
        ),
    ]
