# Generated by Django 5.0.6 on 2024-07-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0008_osiladoraparo_osiladoraproduccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osiladoraproduccion',
            old_name='rollos_osilados',
            new_name='rollo_osilados',
        ),
    ]
