# Generated by Django 5.0.6 on 2024-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0009_rename_rollos_osilados_osiladoraproduccion_rollo_osilados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
