# Generated by Django 5.0.6 on 2024-07-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0010_usuario_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='isAdmin',
        ),
    ]
