# Generated by Django 5.0.6 on 2024-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0011_remove_usuario_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='paro',
            name='linea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='linea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
